services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/app/src
    ports:
      - 3000:3000
    depends_on:
      - db

  db:
    image: postgres:16
    environment:
      - POSTGRES_USER=refactorian
      - POSTGRES_PASSWORD=refactorian
      - POSTGRES_DB=refactorian
    volumes:
      - ./docker/db/data:/var/lib/postgresql/data
      - ./docker/db/sql:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=password
    ports:
      - 5050:80
    depends_on:
      - db

  adminer:
    image: adminer
    ports:
        - 8080:8080
    depends_on:
      - db
